/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.terminalrpg;

import com.example.terminalrpg.entities.creatures.Player;
import com.example.terminalrpg.entities.creatures.playable.Archer;
import com.example.terminalrpg.entities.creatures.playable.Mage;
import com.example.terminalrpg.entities.creatures.playable.Warrior;
import com.example.terminalrpg.utils.Dice;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            var player = createPlayer(sc);
            sc.nextLine();
        }
    }

    public static Player createPlayer(Scanner sc) {
        System.out.println("\nQual o nome do seu Personagem?");

        String name = sc.nextLine();
        System.out.println("\nVocê deseja escolher qual classe para o seu personagem?");
        System.out.println("1. Mago");
        System.out.println("2. Guerreiro");
        System.out.println("3. Arqueiro");
        System.out.println("Digite sua escolha");
        int choice = sc.nextInt();
        while (choice < 1 || choice > 3) {
            System.out.println("Escolha uma opção válida");
            choice = sc.nextInt();
        }
        System.out.println("\nAgora vamos rolar os dados para calcular os atributos do seu personagem");
        sc.nextLine();
        System.out.println("\nRolando dados para o HP (vida)");
        int life = Dice.roll(sc, 3, 6);
        System.out.println("\nRolando dados para o MP (mana)");
        int mana = Dice.roll(sc, 3, 6);
        System.out.println("\nRolando dados para o ATK (ataque)");
        int attack = Dice.roll(sc, 2, 6);
        System.out.println("\nRolando dados para o SPD (velocidade)");
        int speed = Dice.roll(sc, 2, 6);
        System.out.println("\nRolando dados para o LUCK (sorte)");
        int luck = Dice.roll(sc, 2, 6);
        Player player = null;
        
        return player;
    }
}
