/*
 * This source file was generated by the Gradle 'init' task
 */
package terminalrpg;

import java.util.Scanner;
import terminalrpg.managers.GameData;
import terminalrpg.managers.PlayerManager;
import terminalrpg.utils.GameState;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        PlayerManager manager = new PlayerManager(sc);
        GameState state = new GameState();
        GameData game = new GameData();  
        game.startGame(sc, state, manager);
        
        sc.close();
    }   
}
