/*
 * This source file was generated by the Gradle 'init' task
 */
package terminalrpg;

import java.util.Scanner;
import terminalrpg.entities.creatures.Player;
import terminalrpg.entities.creatures.playable.Warrior;
import terminalrpg.entities.itens.Consumable;
import terminalrpg.entities.scene.Scene;
import terminalrpg.managers.GameData;
import terminalrpg.utils.Dice;
import terminalrpg.utils.GameState;

public class App {

    public static void main(String[] args) {
        //try (Scanner sc = new Scanner(System.in)) {
        //    var player = createPlayer(sc);
        //    sc.nextLine();
        //}
        Warrior jogador = new Warrior(10, "Warrior", 100, 20, 20, 10, "Adrian");
        try (Scanner sc = new Scanner(System.in)) {
            GameState state = new GameState();
            GameData game = new GameData();  
            game.startGame(sc, jogador, state);
        }
        
        //Warrior jogador2 = new Warrior(10, "Warrior", 100, 20, 20, 10, "Alex");

        //Scene scn = new Scene("Sala");


        //Consumable potion = new Consumable("Potion");
        //Consumable potion2 = new Consumable("Potion2");
        //jogador.addItem(potion);
        //jogador.addItem(potion2);


        //System.out.println(jogador.getInfo());
        //System.out.println(jogador2.getInfo());
        
        jogador.listInventory();
        
    }

    public static Player createPlayer(Scanner sc) {
        System.out.println("\nQual o nome do seu Personagem?");

        String name = sc.nextLine();
        System.out.println("\nVocê deseja escolher qual classe para o seu personagem?");
        System.out.println("1. Mago");
        System.out.println("2. Guerreiro");
        System.out.println("3. Arqueiro");
        System.out.println("Digite sua escolha");
        int choice = sc.nextInt();
        while (choice < 1 || choice > 3) {
            System.out.println("Escolha uma opção válida");
            choice = sc.nextInt();
        }
        System.out.println("\nAgora vamos rolar os dados para calcular os atributos do seu personagem");
        sc.nextLine();
        System.out.println("\nRolando dados para o HP (vida)");
        int life = Dice.roll(sc, 3, 6);
        System.out.println("\nRolando dados para o MP (mana)");
        int mana = Dice.roll(sc, 3, 6);
        System.out.println("\nRolando dados para o ATK (ataque)");
        int attack = Dice.roll(sc, 2, 6);
        System.out.println("\nRolando dados para o SPD (velocidade)");
        int speed = Dice.roll(sc, 2, 6);
        System.out.println("\nRolando dados para o LUCK (sorte)");
        int luck = Dice.roll(sc, 2, 6);
        Player player = null;
        
        return player;
    }
    
}
