/*
 * This source file was generated by the Gradle 'init' task
 */
package terminalrpg;

import terminalrpg.entities.creatures.Player;
import terminalrpg.entities.creatures.playable.Warrior;
import terminalrpg.entities.itens.Equipable;
import terminalrpg.entities.itens.Item;
import terminalrpg.managers.GameData;

public class Test {

    public static void main(String[] args) {
        Player pl = new Warrior(1, 1, 1, 1, 1, "Adrian");
         pl.addEquipment(new Equipable("Warrior", "Espada", 10, 1, 1, 1, 1));
         pl.addItem(new Item("chave"));
         pl.getInfo();
         System.out.println("\u001B[31mTexto em vermelho\u001B[0m");
        System.out.println(pl.includes("chave"));
        //GameData gm = new GameData();
        //gm.listAll();
    }   

    
}
